version: '3'

vars:
  SOCKET_PATH: /tmp/music-playground.sock

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  run:
    desc: Start all servers (Go + Node.js backend + Vite client) - no audio output
    dir: playground
    cmds:
      - task: kill
      - |
        echo "=== Audio Playground ==="
        echo ""
        echo "Go:      http://localhost:8180"
        echo "Node.js: http://localhost:3000"
        echo "Vite:    http://localhost:5173"
        echo ""
        echo "Press Ctrl+C to stop all servers"
        echo "=========================================="
        echo ""
      - npx concurrently --kill-others --names "Go,Node,Vite" --prefix-colors "cyan,green,magenta" --prefix "[{name}]" "cd .. && go run cmd/playground/main.go" "npm run dev" "cd client && npx vite --clearScreen false"

  run:debug:
    desc: Start all servers with DEBUG mode (audio plays to macOS speakers)
    dir: playground
    cmds:
      - task: kill
      - |
        echo "=== Audio Playground (DEBUG MODE) ==="
        echo "Audio: PCM s16le 48kHz -> ffplay -> macOS speakers"
        echo ""
        echo "Go:      http://localhost:8180"
        echo "Node.js: http://localhost:3000"
        echo "Vite:    http://localhost:5173"
        echo ""
        echo "Press Ctrl+C to stop all servers"
        echo "=========================================="
        echo ""
      - npx concurrently --kill-others --names "Go,Node,Vite" --prefix-colors "cyan,green,magenta" --prefix "[{name}]" "cd .. && go run cmd/playground/main.go" "DEBUG_AUDIO=1 npm run dev" "cd client && npx vite --clearScreen false"

  go:
    desc: Start only Go server
    cmds:
      - task: kill
      - go run cmd/playground/main.go

  node:
    desc: Start only Node.js server
    dir: playground
    cmds:
      - npm run dev

  client:
    desc: Start only Vite client (React frontend)
    dir: playground/client
    cmds:
      - npm run dev

  kill:
    desc: Kill any running playground servers
    cmds:
      - |
        pkill -f "go run cmd/playground" 2>/dev/null || true
        pkill -f "cmd/playground/main" 2>/dev/null || true
        pkill -f "playground/dist/index.js" 2>/dev/null || true
        pkill -f "node dist/index.js" 2>/dev/null || true
        pkill -f "vite" 2>/dev/null || true
        pkill -f "playground/client" 2>/dev/null || true
        rm -f {{.SOCKET_PATH}}
        echo "Killed existing servers"

  build:
    desc: Build everything
    cmds:
      - go build -o bin/playground cmd/playground/main.go
      - cd playground && npm run build
      - cd playground/client && npm run build
      - echo "Build complete"

  install:
    desc: Install dependencies
    cmds:
      - cd playground && npm install
      - cd playground/client && npm install
      - echo "Dependencies installed"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf playground/dist/
      - rm -rf playground/client/dist/
      - rm -f {{.SOCKET_PATH}}
      - echo "Cleaned"
