version: '3'

vars:
  SOCKET_PATH: /tmp/music-playground.sock

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  run:
    desc: Start all servers (Go + Node.js backend + Vite client) - no audio output
    cmds:
      - task: kill
      - |
        echo "=== Audio Playground ==="
        echo ""
        echo "Starting Go server in background..."
        go run cmd/playground/main.go &
        GO_PID=$!
        echo "Go server PID: $GO_PID"
        sleep 2

        echo ""
        echo "Starting Node.js backend in background..."
        cd playground && npm run dev &
        NODE_PID=$!
        echo "Node.js server PID: $NODE_PID"
        sleep 2

        echo ""
        echo "Starting Vite client..."
        echo "Open http://localhost:5173 in your browser"
        echo "Press Ctrl+C to stop all servers"
        echo ""

        cd playground/client && npm run dev

        # When Vite exits, kill Go and Node
        kill $GO_PID 2>/dev/null || true
        kill $NODE_PID 2>/dev/null || true

  run:debug:
    desc: Start all servers with DEBUG mode (audio plays to macOS speakers)
    cmds:
      - task: kill
      - |
        echo "=== Audio Playground (DEBUG MODE) ==="
        echo ""
        echo "Starting Go server in background..."
        go run cmd/playground/main.go &
        GO_PID=$!
        echo "Go server PID: $GO_PID"
        sleep 2

        echo ""
        echo "Starting Node.js backend in background (DEBUG=1)..."
        cd playground && DEBUG_AUDIO=1 npm run dev &
        NODE_PID=$!
        echo "Node.js server PID: $NODE_PID"
        sleep 2

        echo ""
        echo "Starting Vite client..."
        echo "Open http://localhost:5173 in your browser"
        echo "Audio will play to macOS speakers!"
        echo "Press Ctrl+C to stop all servers"
        echo ""

        cd playground/client && npm run dev

        # When Vite exits, kill Go and Node
        kill $GO_PID 2>/dev/null || true
        kill $NODE_PID 2>/dev/null || true

  go:
    desc: Start only Go server
    cmds:
      - task: kill
      - go run cmd/playground/main.go

  node:
    desc: Start only Node.js server
    dir: playground
    cmds:
      - npm run dev

  client:
    desc: Start only Vite client (React frontend)
    dir: playground/client
    cmds:
      - npm run dev

  kill:
    desc: Kill any running playground servers
    cmds:
      - |
        pkill -f "go run cmd/playground" 2>/dev/null || true
        pkill -f "cmd/playground/main" 2>/dev/null || true
        pkill -f "playground/dist/index.js" 2>/dev/null || true
        pkill -f "node dist/index.js" 2>/dev/null || true
        pkill -f "vite" 2>/dev/null || true
        pkill -f "playground/client" 2>/dev/null || true
        rm -f {{.SOCKET_PATH}}
        echo "Killed existing servers"

  build:
    desc: Build everything
    cmds:
      - go build -o bin/playground cmd/playground/main.go
      - cd playground && npm run build
      - cd playground/client && npm run build
      - echo "Build complete"

  install:
    desc: Install dependencies
    cmds:
      - cd playground && npm install
      - cd playground/client && npm install
      - echo "Dependencies installed"

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf playground/dist/
      - rm -rf playground/client/dist/
      - rm -f {{.SOCKET_PATH}}
      - echo "Cleaned"
